version: "3.9"
services:
  zookeeper:
    build: ./zookeeper/
    command: bash -c "/kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties & /usr/bin/prometheus-node-exporter"
    container_name: zookeeper
    ports:
     - "2181:2181"
     - "9102:9100"
    networks:
     - kafka_network
    volumes:
     - ./zookeeper/logs_zookeeper/:/kafka/logs/

  kafka_node_1:
    build: ./kafka_node_1/
    command: bash -c "/kafka/bin/kafka-server-start.sh kafka/config/server.properties & /usr/bin/prometheus-node-exporter"
    container_name: kafka_node_1
    ports:
     - "9092:9092"
     - "9100:9100"
    links:
     - zookeeper
    depends_on:
     - zookeeper
    networks:
     - kafka_network
    volumes:
     - ./kafka_node_1/logs_kafka/:/kafka/logs/


  kafka_node_2:
    build: ./kafka_node_2/
    command: bash -c "/kafka/bin/kafka-server-start.sh kafka/config/server.properties & /usr/bin/prometheus-node-exporter"
    container_name: kafka_node_2
    ports:
     - "9091:9092"
     - "9101:9100"
    links:
     - zookeeper
    depends_on:
     - zookeeper
    networks:
     - kafka_network
    volumes:
     - ./kafka_node_2/logs_kafka/:/kafka/logs/
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
      - 9104:9000
    networks:
      - kafka_network 
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    user: root
    ports:
      - 9000:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - kafka_network

networks:
  kafka_network:
